package prompt

import (
	"encoding/json"
	"strings"
)

type sdkCompactSuffix struct {
	bytes int
	hash  string
}

// Complete v140609 wrapper scaffolds, generated by all eight boolean-option
// combinations of the reviewed native factory. Only hashes are published.
// The optional transcript path is transient and never enters tracker state.
const sdkCompactPrefixBytes = 153
const sdkCompactPrefixHash = "2e9b0a6ae237758edd9c077abd7254caf76aa2646d754bb1a150e9c59a847e92"
const sdkCompactPathPrefixBytes = 153
const sdkCompactPathPrefixHash = "6f59dd624d090f377450200b9ae0e48b572d4d76f10cc2563195cfd7ab358208"

var sdkCompactSuffixes = []sdkCompactSuffix{
	{0, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"},
	{41, "4754cc91957abce6baba7aa4c34471bf44a5b2c197688221a0194ee74b978aa9"},
	{173, "20c9096056071f6b6e972714fb38e8931ca40df9d0b7bce35407a5c2d59dc20d"},
	{214, "79b99e69b289bce8f3ef678055a7eb03d6e44dde677cd1e324571eac1fb8d686"},
	{283, "4b28b551effbf142cc452545a0e034405234441841f1e5b9c6aaec6e54a31cce"},
	{324, "7ee11cbd9d99252af3b6c71ca9c6eb212c14341a9e9e7131f36eecde53bf92cd"},
	{456, "31b2d326702ac2692bb17a69feb429c3e8f3d019a39b1c13f7e3f34e9b420109"},
	{497, "908cb1071d79cd4fe41e05f716959d85c54732d2b1e21f020424c2a652e1942f"},
}

func (s SDKCompactionSummary) matches(text string) bool {
	if !s.reviewed || s.bytes < 0 || len(text) < sdkCompactPrefixBytes+s.bytes ||
		sdkCompactionHash(text[:sdkCompactPrefixBytes]) != sdkCompactPrefixHash {
		return false
	}
	end := sdkCompactPrefixBytes + s.bytes
	if sdkCompactionHash(text[sdkCompactPrefixBytes:end]) != s.sha256 {
		return false
	}
	return sdkCompactSuffixMatches(text[end:], sdkCompactSuffixes, sdkCompactPathPrefixBytes, sdkCompactPathPrefixHash)
}

func sdkCompactSuffixMatches(rest string, suffixes []sdkCompactSuffix, pathPrefixBytes int, pathPrefixHash string) bool {
	matches := 0
	for _, suffix := range suffixes {
		if suffix.bytes < 0 || len(rest) < suffix.bytes || sdkCompactionHash(rest[len(rest)-suffix.bytes:]) != suffix.hash {
			continue
		}
		prefix := rest[:len(rest)-suffix.bytes]
		if prefix == "" {
			matches++
			continue
		}
		if pathPrefixBytes <= 0 || len(prefix) <= pathPrefixBytes || len(prefix)-pathPrefixBytes > 32768 ||
			sdkCompactionHash(prefix[:pathPrefixBytes]) != pathPrefixHash || strings.ContainsAny(prefix[pathPrefixBytes:], "\r\n") {
			continue
		}
		matches++
	}
	return matches == 1
}

type sdkCompaction struct {
	observation SDKCompactionObservation
	applied     bool
	discarded   bool
}

type sdkCompactionHistory struct {
	firstUserTexts []string
	otherTexts     []string
	simple         bool
	known          bool
}

// A version-reviewed wrapper corroborates content only. Explicit parent
// ownership and a previously completed helper are checked separately.
func observeSDKCompactionHistory(body []byte) sdkCompactionHistory {
	var input struct {
		Messages []struct {
			Role    string          `json:"role"`
			Content json.RawMessage `json:"content"`
		} `json:"messages"`
	}
	if json.Unmarshal(body, &input) != nil || len(input.Messages) == 0 {
		return sdkCompactionHistory{}
	}
	result := sdkCompactionHistory{known: true, simple: true}
	rows := 0
	for _, message := range input.Messages {
		if message.Role == "system" {
			continue
		}
		rows++
		if rows == 1 && message.Role != "user" {
			return sdkCompactionHistory{}
		}
		if rows > 1 {
			result.simple = false
		}
		if message.Role != "user" {
			continue
		}
		var texts []string
		var text string
		if json.Unmarshal(message.Content, &text) == nil {
			texts = []string{text}
		} else {
			var blocks []struct {
				Type string `json:"type"`
				Text string `json:"text"`
			}
			if json.Unmarshal(message.Content, &blocks) != nil {
				return sdkCompactionHistory{}
			}
			if len(blocks) != 1 {
				result.simple = false
			}
			for _, block := range blocks {
				if block.Type == "text" {
					texts = append(texts, block.Text)
				}
			}
		}
		if rows == 1 {
			result.firstUserTexts = texts
		} else {
			result.otherTexts = append(result.otherTexts, texts...)
		}
	}
	return result
}

func (s *sdkAccounting) matchCompaction(history sdkCompactionHistory) (string, bool) {
	if !history.known {
		return "", false
	}
	matched := ""
	for key, operation := range s.compactions {
		if operation.applied || operation.discarded || !operation.observation.input.known {
			continue
		}
		count := 0
		for _, text := range history.firstUserTexts {
			if operation.observation.summary.matches(text) {
				count++
			}
		}
		if count == 0 {
			continue
		}
		for _, text := range history.otherTexts {
			if operation.observation.summary.matches(text) {
				count++
			}
		}
		if count != 1 || matched != "" {
			return "", false
		}
		matched = key
	}
	return matched, !history.simple
}

// applySDKCompaction runs only when the bound continuation reaches the actual
// upstream request observer. Selection/response success alone cannot call it.
// A new canonical summary user object and scan boundary are owned here; hidden
// native hook/attachment yields remain unknown when wire history is not simple.
func (c *call) applySDKCompaction(body []byte) {
	if c.compactionKey == "" {
		return
	}
	s := c.state
	operation := s.sdk.compactions[c.compactionKey]
	if operation == nil || operation.applied || operation.discarded || s.sdk.result != nil {
		return
	}
	// Planning can precede translation or body rewriting. Only the final
	// observed wire body proves adoption; selection's input is not sufficient.
	key, unknownYields := s.sdk.matchCompaction(observeSDKCompactionHistory(body))
	if key != c.compactionKey {
		s.sdk.incompleteReason = "unobserved-sdk-compaction-adoption"
		return
	}
	operation.applied = true
	s.sdk.pendingCompactions--
	for id := range s.pending {
		if _, observed := operation.observation.input.toolResults[id]; !observed {
			s.incompleteReason = "unobserved-precompact-tool-result"
			continue
		}
		delete(s.pending, id)
		s.toolResults++
		s.sdk.yieldUser(sdkToolResultUserYield)
	}
	// The canonical boundary is owned by actual application, not the helper's
	// API success. Precompact results belong before this boundary. Unobserved
	// preserved/hook yields cannot be recovered from normalized HTTP rows.
	s.sdk.history.boundary()
	if c.compactionUnknownYields || unknownYields {
		s.sdk.history.unknown("unobserved-sdk-compaction-preserved-history")
	}
	s.sdk.yieldUser(sdkCompactionSummaryUserYield)
	if !c.compactionUnknownYields && !unknownYields {
		c.sdkUserHistoryOffsets = []int{len(s.sdk.history.messages) - 1}
	}
	s.sdk.sawCompact = true
	s.sdk.tools = nil
	s.sdk.unknownCompactionYields = s.sdk.unknownCompactionYields || c.compactionUnknownYields || unknownYields
}
